import db from "@/lib/prisma";

// ---------------------------------------------------------------------------
// Types — mirrors the JSON structure generated by the LLM script
// ---------------------------------------------------------------------------

export interface MasterProfileStyle {
  concentration: string;
  holdingCount: string;
  sectorFocus: string[];
  turnover: string;
  avgHoldingPeriod: string;
  leverageUsage: string;
}

export interface MasterProfileFlagshipCase {
  ticker: string;
  nameZh: string;
  entryYear: number;
  thesis: string;
  outcome: string;
  stillHolding: boolean;
}

export interface MasterProfileTrackRecord {
  startYear: number | null;
  cagr: string | null;
  benchmarkComparison: string | null;
  sourceNote: string;
}

export interface MasterProfileData {
  intro: string;
  framework: string[];
  tags: string[];
  timeline: string[];
  style: MasterProfileStyle;
  flagshipCases: MasterProfileFlagshipCase[];
  influences: string[];
  quotes: string[];
  trackRecord: MasterProfileTrackRecord | null;
}

export interface MasterProfileResult {
  profile: MasterProfileData;
  source: string;
  version: number;
  generatedAt: Date;
}

// ---------------------------------------------------------------------------
// Query
// ---------------------------------------------------------------------------

export async function getMasterProfile(
  tribeId: string,
): Promise<MasterProfileResult | null> {
  try {
    const row = await db.masterProfile.findFirst({
      where: { entity: { tribeId } },
      select: {
        profile: true,
        source: true,
        version: true,
        generatedAt: true,
      },
    });

    if (!row) return null;

    return {
      profile: row.profile as unknown as MasterProfileData,
      source: row.source,
      version: row.version,
      generatedAt: row.generatedAt,
    };
  } catch {
    return null;
  }
}
